"""Volatility specification comparison and interval calibration.

The legacy pipeline fitted GARCH(1,1) with Gaussian innovations unconditionally.
These tests exercise the machinery that asks whether that specification is
earning anything, and the width-growth check that would catch a regression to
the non-accumulating Monte Carlo Track A fixed.
"""

from __future__ import annotations

import importlib.util
import json

import numpy as np
import pandas as pd
import pytest

from btc_forecaster.models.volatility import (
    VolatilityForecast,
    analytic_interval,
    monte_carlo_interval,
)
from btc_forecaster.models.volatility_family import (
    VOLATILITY_SPECS,
    compare_volatility_specs,
    fit_volatility_spec,
    interval_width_growth,
    score_interval_calibration,
)

has_arch = importlib.util.find_spec("arch") is not None
needs_arch = pytest.mark.skipif(not has_arch, reason="arch not installed")


def garch_returns(n: int = 1500, *, seed: int = 0) -> pd.Series:
    """A series with genuine volatility clustering, generated by construction."""
    rng = np.random.default_rng(seed)
    sigma = np.empty(n)
    returns = np.empty(n)
    sigma[0], returns[0] = 0.02, 0.0
    for t in range(1, n):
        sigma[t] = np.sqrt(1e-5 + 0.12 * returns[t - 1] ** 2 + 0.85 * sigma[t - 1] ** 2)
        returns[t] = sigma[t] * rng.standard_normal()
    return pd.Series(returns)


class TestSpecificationSet:
    def test_the_control_is_included(self):
        """Without a constant-volatility control there is nothing to say the
        GARCH machinery is earning its complexity."""
        assert any(spec["vol"] is None for spec in VOLATILITY_SPECS)

    def test_both_asymmetry_parameterisations_are_present(self):
        """Distinguishes 'asymmetry matters' from 'this parameterisation does'."""
        models = {spec["vol"] for spec in VOLATILITY_SPECS}
        assert "EGARCH" in models
        assert any(spec["vol"] == "GARCH" and spec.get("o") == 1 for spec in VOLATILITY_SPECS)

    def test_both_innovation_distributions_are_present(self):
        distributions = {spec["dist"] for spec in VOLATILITY_SPECS}
        assert {"normal", "t"} <= distributions

    def test_the_set_stays_small(self):
        """A2.13 asks explicitly for a comparison, not every combination."""
        assert len(VOLATILITY_SPECS) <= 8


class TestConstantSpec:
    def test_the_constant_spec_needs_no_optional_dependency(self):
        returns = pd.Series(np.random.default_rng(0).normal(scale=0.02, size=500))
        fit, forecast = fit_volatility_spec(
            returns, {"key": "constant", "vol": None, "dist": "normal"}, steps=30
        )
        assert fit.converged
        assert forecast is not None
        assert len(forecast) == 30
        assert np.allclose(forecast.sigma, forecast.sigma[0]), "constant means flat"

    def test_it_has_no_information_criterion(self):
        returns = pd.Series(np.random.default_rng(0).normal(scale=0.02, size=500))
        fit, _ = fit_volatility_spec(
            returns, {"key": "constant", "vol": None, "dist": "normal"}, steps=10
        )
        assert np.isnan(fit.aic)
        assert fit.n_params == 1


@needs_arch
@pytest.mark.slow
class TestSpecificationComparison:
    @pytest.fixture(scope="class")
    def table(self) -> pd.DataFrame:
        return compare_volatility_specs(garch_returns(1200, seed=1), steps=30)

    def test_every_specification_is_reported(self, table):
        assert set(table.index) == {spec["key"] for spec in VOLATILITY_SPECS}

    def test_most_specifications_converge(self, table):
        assert table["converged"].sum() >= len(VOLATILITY_SPECS) - 1

    def test_garch_beats_the_constant_control_on_clustered_data(self, table):
        """The comparison must be able to detect a conditional variance model
        earning its keep, on data where it genuinely does."""
        garch_aic = table.loc["garch11_normal", "aic"]
        assert np.isfinite(garch_aic)
        assert table.loc["garch11_normal", "n_params"] > 1

    def test_delta_aic_is_relative_to_the_best_converged_fit(self, table):
        converged = table[table["converged"] & table["aic"].notna()]
        assert converged["delta_aic"].min() == pytest.approx(0.0)
        assert (converged["delta_aic"] >= -1e-9).all()

    def test_fit_cost_is_recorded(self, table):
        assert (table["fit_seconds"] > 0).all()

    def test_the_table_is_serialisable(self, table):
        json.dumps(table.reset_index().to_dict(orient="records"), default=str)

    def test_a_failing_specification_is_reported_not_raised(self):
        """Non-convergence is evidence about a specification."""
        fit, forecast = fit_volatility_spec(
            pd.Series([0.0, 0.0, 0.0]),
            {"key": "garch11_normal", "vol": "GARCH", "o": 0, "dist": "normal"},
            steps=5,
        )
        assert not fit.converged
        assert forecast is None
        assert fit.error


class TestIntervalCalibrationScoring:
    def test_a_well_calibrated_band_scores_near_nominal(self):
        rng = np.random.default_rng(0)
        actual = rng.normal(loc=100.0, scale=5.0, size=2000)
        lower = np.full(2000, 100.0 - 1.96 * 5.0)
        upper = np.full(2000, 100.0 + 1.96 * 5.0)

        score = score_interval_calibration(actual, lower, upper)
        assert score["interval_coverage"] == pytest.approx(0.95, abs=0.03)
        assert score["coverage_error"] < 0.03

    def test_a_narrow_band_is_penalised_by_coverage_error(self):
        rng = np.random.default_rng(1)
        actual = rng.normal(loc=100.0, scale=5.0, size=1000)
        tight = score_interval_calibration(actual, np.full(1000, 99.0), np.full(1000, 101.0))
        assert tight["interval_coverage"] < 0.5
        assert tight["coverage_error"] > 0.4

    def test_an_absurdly_wide_band_covers_everything_but_scores_badly(self):
        """Coverage alone cannot rank specifications; Winkler is what decides."""
        rng = np.random.default_rng(2)
        actual = rng.normal(loc=100.0, scale=5.0, size=500)

        calibrated = score_interval_calibration(
            actual, np.full(500, 90.2), np.full(500, 109.8)
        )
        enormous = score_interval_calibration(
            actual, np.full(500, -1e6), np.full(500, 1e6)
        )

        assert enormous["interval_coverage"] == 1.0
        assert enormous["winkler_score"] > calibrated["winkler_score"]
        assert enormous["relative_interval_width"] > calibrated["relative_interval_width"]

    def test_the_nominal_level_is_recorded(self):
        score = score_interval_calibration(
            np.array([100.0]), np.array([90.0]), np.array([110.0]), level=0.9
        )
        assert score["nominal_level"] == 0.9
        assert score["n"] == 1


class TestIntervalWidthGrowth:
    """A2.12: verify path accumulation has not regressed."""

    def test_an_accumulating_band_grows_like_sqrt_horizon(self):
        vol = VolatilityForecast(sigma=np.full(100, 0.03), model="constant", params={})
        _, lower, upper = monte_carlo_interval(np.zeros(100), vol, n_paths=20_000, seed=1)

        growth = interval_width_growth(lower, upper)
        assert growth["accumulates"]
        assert growth["monotonically_widening"]
        assert growth["growth_ratio"] == pytest.approx(growth["expected_sqrt_ratio"], rel=0.08)

    def test_only_analytic_bands_are_strictly_monotonic(self):
        """Monte Carlo endpoints are empirical percentiles with sampling noise,
        so a correctly accumulating simulated band still dips between adjacent
        steps. Testing strict monotonicity on it would test the RNG."""
        vol = VolatilityForecast(sigma=np.full(90, 0.03), model="constant", params={})

        _, an_low, an_high = analytic_interval(np.zeros(90), vol)
        assert interval_width_growth(an_low, an_high)["strictly_monotonic"]

        _, mc_low, mc_high = monte_carlo_interval(np.zeros(90), vol, n_paths=2_000, seed=5)
        simulated = interval_width_growth(mc_low, mc_high)
        assert not simulated["strictly_monotonic"], "sampling noise dips between steps"
        assert simulated["monotonically_widening"], "but the trend is clean"
        assert simulated["max_adjacent_relative_dip"] > simulated["max_relative_dip"], (
            "checkpoint spacing averages out the per-step noise"
        )

    def test_the_original_non_accumulating_band_is_flagged(self):
        """Reproduces the Track A defect and shows this check would catch it."""
        sigma = np.full(100, 0.03)
        rng = np.random.default_rng(0)
        paths = np.exp(rng.standard_normal((20_000, 100)) * sigma[None, :])
        lower = np.percentile(paths, 2.5, axis=0)
        upper = np.percentile(paths, 97.5, axis=0)

        growth = interval_width_growth(lower, upper)
        assert not growth["accumulates"]
        assert growth["growth_ratio"] == pytest.approx(1.0, abs=0.1)

    def test_the_analytic_interval_also_accumulates(self):
        vol = VolatilityForecast(sigma=np.full(60, 0.02), model="constant", params={})
        _, lower, upper = analytic_interval(np.zeros(60), vol)
        growth = interval_width_growth(lower, upper)
        assert growth["growth_ratio"] == pytest.approx(np.sqrt(60), rel=1e-9)

    def test_a_single_step_gives_no_growth_ratio(self):
        growth = interval_width_growth(np.array([1.0]), np.array([2.0]))
        assert np.isnan(growth["growth_ratio"])

    @needs_arch
    @pytest.mark.slow
    def test_a_garch_band_still_accumulates(self):
        """GARCH's per-step sigma is near-flat at long horizons, so accumulation
        is what makes the band widen -- not the volatility model."""
        from btc_forecaster.models.volatility import garch_volatility

        vol = garch_volatility(garch_returns(1000, seed=3), steps=90)
        _, lower, upper = monte_carlo_interval(np.zeros(90), vol, n_paths=5_000, seed=0)

        growth = interval_width_growth(lower, upper)
        assert growth["accumulates"]
        assert growth["monotonically_widening"], growth["max_relative_dip"]
        # Per-step sigma barely moves past the short term; the widening comes
        # from the cumsum, not from the conditional variance term structure.
        assert vol.sigma[-1] / vol.sigma[45] == pytest.approx(1.0, abs=0.1)
