"""The run directory's own README, generated from the canonical results.

A reader who opens ``research/runs/a7-walk-forward/`` must meet the decision and
the scientific status before any number, and must be able to tell from the
README alone what was compared, what failed which gate, and how to check the
result. Generated rather than written, so a rerun cannot leave a confident
summary of a previous run standing.
"""

from __future__ import annotations

from collections.abc import Callable

from .manifest import InputManifest
from .runner import BenchmarkOutcome
from .targets import TARGET_DEFINITION


def _fmt(value: object) -> str:
    if isinstance(value, float):
        return f"{value:+.4f}"
    return str(value)


def readme_builder(outcome: BenchmarkOutcome, input_manifest: InputManifest) -> Callable[[dict], str]:
    """A function from the finished manifest to README text."""

    def build(manifest: dict) -> str:
        config, schedule, decision, family = outcome.config, outcome.schedule, outcome.decision, outcome.family
        source = input_manifest.as_dict()
        lines = [
            "# A7 walk-forward robustness -- run evidence",
            "",
            f"**Decision: `{decision['decision']}`.** Scientific status: EXPLORATORY. "
            "No model is promoted and live trading stays disabled; A7 has no state "
            "that could do otherwise.",
            "",
            "Generated by `python -m btc_forecaster.research.walk_forward`. Nothing in "
            "this directory is written by hand. Methodology: "
            "[`docs/walk-forward.md`](../../../docs/walk-forward.md).",
            "",
            "## What was asked",
            "",
            f"- Models: {', '.join(f'`{m}`' for m in config.models)}",
            f"- Horizons: {', '.join(str(h) for h in config.horizons)} bars; target "
            f"`{TARGET_DEFINITION['formula']}`, {TARGET_DEFINITION['units']}",
            f"- Training windows: {', '.join(w.label for w in config.windows)}",
            f"- Origins: {len(schedule.origins)} daily origins, "
            f"{schedule.origins[0].date()} to {schedule.origins[-1].date()}, "
            f"refit at {len(schedule.folds)} folds; blocks {', '.join(schedule.block_names)}",
            f"- Configurations gated: {decision['configurations_evaluated']}",
            "",
            "## The decision",
            "",
            f"- Candidates clearing every gate: **{len(decision['candidates'])}**",
            f"- Fragile signals: **{len(decision['fragile_signals'])}**",
            f"- Statistically different from naive after BH: {decision['statistically_different']}",
            f"- Statistically better: {decision['statistically_better']}",
            f"- Practically useful: {decision['practically_useful']}",
            "",
            "Multiple testing: "
            f"{family.get('family_size', 0)} comparisons at alpha {family.get('alpha')}; "
            f"{family.get('raw_significant', 0)} raw rejections against "
            f"{family.get('expected_false_positives_at_alpha', 0):.1f} expected from noise; "
            f"{family.get('significantly_better_after_bh', 0)} better and "
            f"{family.get('significantly_worse_after_bh', 0)} worse after Benjamini-Hochberg.",
            "",
            "Gate failures across all configurations:",
            "",
            "| gate | failed |",
            "|---|---|",
            *[f"| `{name}` | {count} |" for name, count in decision["gate_failure_counts"].items()],
            "",
        ]
        if decision["fragile_signals"]:
            lines += ["### Fragile signals, and the gates they failed", "", "| model | h | window | failed |", "|---|---|---|---|"]
            lines += [
                f"| `{s['model_id']}` | {s['horizon']} | {s['window']} | {', '.join(s['failed'])} |"
                for s in decision["fragile_signals"]
            ]
            lines.append("")
        if decision["candidates"]:
            lines += ["### Candidates", "", "| model | h | window |", "|---|---|---|"]
            lines += [f"| `{c['model_id']}` | {c['horizon']} | {c['window']} |" for c in decision["candidates"]]
            lines += [
                "",
                "A candidate merits a separate, preregistered study. It is not a model "
                "to trade, and nothing in this repository will trade it.",
                "",
            ]
        lines += [
            "## Input",
            "",
            f"- `{source['source']['ticker']}` via {source['source']['provider']}, retrieved "
            f"{source['source']['retrieved_at']}, {source['rows']} bars "
            f"{source['range']['start'][:10]} to {source['range']['end'][:10]}",
            f"- Frame sha256 `{input_manifest.frame_sha256}`",
            f"- {source['licence']}",
            "",
            "## Reproducing and checking",
            "",
            f"- Result digest **`{manifest['result_digest']}`**, over "
            f"{', '.join(f'`{f}`' for f in manifest['digest_covers'])}.",
            "- Timings, the environment and this README are outside it: they describe the "
            "machine and the moment, not the result.",
            "- `python -m btc_forecaster.research.walk_forward verify <this directory>` "
            "recomputes every hash from disk.",
            "- A rerun on an input with a different frame sha256 is a different "
            "experiment, and the command refuses to call it a reproduction.",
            "",
            "## What this is not",
            "",
            "- Not comparable to A2, which scored a 31-step price path in USD.",
            "- Not a re-statement of A6. A6 fitted once on 1,000 rows and scored one block "
            "at h = 1; this re-asks across origins, horizons, windows and periods.",
            "- Not a trading signal, under any decision.",
            "",
        ]
        return "\n".join(lines)

    return build


__all__ = ["readme_builder"]
