"""Point-in-time feature construction and train-only selection."""

from .pipeline import (
    SupervisedData,
    assert_causal,
    build_feature_frame,
    future_feature_row,
    required_history,
    summarise_features,
    target_log_price,
    target_simple_return,
    to_supervised,
)
from .selection import FeatureSelection, FeatureSelector, select_pacf_lags
from .spec import (
    Ema,
    FeatureSpec,
    LagReturn,
    PriceOverSma,
    RollingMeanReturn,
    RollingMeanVolume,
    RollingStdReturn,
    Sma,
    default_specs,
    log_price,
    log_returns,
    simple_returns,
)

__all__ = [
    "Ema",
    "FeatureSelection",
    "FeatureSelector",
    "FeatureSpec",
    "LagReturn",
    "PriceOverSma",
    "RollingMeanReturn",
    "RollingMeanVolume",
    "RollingStdReturn",
    "Sma",
    "SupervisedData",
    "assert_causal",
    "build_feature_frame",
    "default_specs",
    "future_feature_row",
    "log_price",
    "log_returns",
    "required_history",
    "select_pacf_lags",
    "simple_returns",
    "summarise_features",
    "target_log_price",
    "target_simple_return",
    "to_supervised",
]
